services:
  _defaults:
    autowire: true
    autoconfigure: true
  RobertvanLienden\UserAgreements\:
    resource: '../../'
    exclude:
      - '../../Entity/'
  RobertvanLienden\UserAgreements\EventListener\DoctrineMetadataListener:
    arguments:
      $userEntityClass: '%user_agreements.user_entity%'  # Pass the user entity class dynamically
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }