name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f development/Dockerfile -t php-ci .

      - name: Save Docker image as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: |
            $(docker save php-ci | gzip > image.tar.gz)
