name: Run Code Style Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: ./image.tar.gz

      - name: Load Docker image
        run: |
          docker load < ./image.tar.gz

      - name: Run codestyle tests
        run: |
          docker run --rm php-ci ./Taskfile codestyle