name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f development/Dockerfile -t php-ci .

      - name: Run codestyle tests
        run: |
          docker run --rm php-ci vendor/bin/ecs --config=development/tooling/ecs.php

      - name: Run PHPStan
        run: |
          docker run --rm php-ci vendor/bin/phpstan --configuration=./development/tooling/phpstan.neon

      - name: Run unit tests with coverage
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace php-ci vendor/bin/phpunit -c development/tooling/phpunit.xml --testdox tests --coverage-clover=/workspace/coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
           slug: robertvanlienden/useragreementsbundle